Task5.1
Charlotte000/Homework pull request #11
Opened 2020-10-27 15:26 UTC by Charlotte000

2020-10-28 12:49 UTC, yurii-litvinov requested changes
В принципе, всё ок, надо только тесты ещё

2020-10-28 12:49 UTC, yurii-litvinov commented on 5.1/Stack.c
> +#include <stdbool.h>
Надо свой заголовочный файл ещё подключать

2020-11-04 10:25 UTC, yurii-litvinov requested changes

2020-11-04 10:25 UTC, yurii-litvinov commented on Task5/5.1/Source.c
> +	int value1, value2;
О, неинициализированные переменные, к тому же объявленные две сразу, по стайлгайду так нельзя :)

2020-11-04 10:25 UTC, yurii-litvinov commented on Task5/5.1/Source.c
> +}
Тесты на стек --- это хорошо. А тесты на, ээ, всё остальное? Вы бы стали пользоваться, например, банковской системой, в которой известно, что работает реализация стека, а остальное никто никогда не проверял? :)

2020-11-08 12:12 UTC, Charlotte000 commented on Task5/5.1/Source.c
> +}
А тесты на что делать? Сама программа практически состоит из стека.

2021-02-13 10:02 UTC, merged