Task 2.1
Charlotte000/Homework pull request #29
Opened 2021-02-20 18:55 UTC by Charlotte000

2021-02-21 12:39 UTC, yurii-litvinov requested changes
Тут как-то совсем мимо ООП, как будто пары в пятницу не было :) Пока 2 из 7 (точнее даже из 8 за BWT, но за него придётся хорошо побороться).

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/BWTalgoritm.cs
> +    class BWTalgoritm
CamelCase. BwtAlgorit**h**m или хотя бы BWTAlgorithm

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/BWTalgoritm.cs
> +
Лишние пустые строки

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/BWTalgoritm.cs
> +        const char StopCharacter = '$';
Теперь вы уже знаете про модификаторы видимости, поэтому теперь надо везде писать private

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/LZWalgoritm.cs
> +    class LZWalgoritm
Тут тоже название не очень, надо переименовать класс и файл

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/LZWalgoritm.cs
> +            Trie head = new Trie();
var

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/LZWalgoritm.cs
> +            FileStream file = File.OpenWrite(compressedPath);
Я про это ещё не рассказывал, но вообще надо писать `using FileStream file = File.OpenWrite(compressedPath);`, чтобы файл закрылся даже если будет брошено исключение.

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Trie.cs
> +        public int childrenLen;
Это можно прокомментировать одним словом: **инкапсуляция!**

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/file.txt
> +.........lttcmrttsiao,,,dmgtms,et,risrmeseatman,rasmdsiecmcnsoctr,tmstm,a,c.ttcailsiammtrttasec   $      d  ltlsn   fu tm iuN  lldnvmu  p Mirriienaaeansrias  euueiniia  ra nrauturnnslrrvvc  Prrth lml
Типичный файл, на котором удобно тестить архиватор :)

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Trie.cs
> +            children = new Trie[300];
Мм. Обычно в реализации бора как-то участвует хеш-таблица (можно библиотечную).

Ну либо рассматривайте сжимаемый файл как бинарник и работайте с byte, а не с char. Их всего 255. Всё равно проверять я буду на .exe-файлах --- если запустится после распаковки, ок :)

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/LZWalgoritm.cs
> +                    cursor.AddChild(input[charIndex]).value = index++;
Нельзя побочные эффекты в выражениях по стайлгайду. Не заметите в жизни этот ++

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/LZWalgoritm.cs
> +                        file.WriteByte(255);
255 вполне может быть валидным символом

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/LZWalgoritm.cs
> +            FileStream fileRead = File.OpenRead(path);
Тут тоже надо using добавить

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/LZWalgoritm.cs
> +            int[,] dictionary = new int[fileRead.Length / 2, 2];
var

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Program.cs
> +                        File.WriteAllText(path, BWTalgoritm.BWT(File.ReadAllText(path)));
Плохая идея, портит исходный файл

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Program.cs
> +                    FileInfo origin = new FileInfo(path);
var

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Program.cs
> +                        File.WriteAllText(path, BWTalgoritm.BWT(File.ReadAllText(path)));
Кстати, просили именно поииследовать влияние BWT на коэффициент сжатия. То есть хочется отдельный метод, который бы посжимал десяток разных файлов (текстов, бинарников, что-нить уже жатое типа .pdf или .jpg) с и без, нашёл бы матожидание и дисперсию коэффициента сжатия с и без.

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Program.cs
> +
Лишняя пустая строчка

2021-02-21 12:39 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/BWTalgoritm.cs
> +        const char StopCharacter = '$';
Да, и тут уже всё-таки речь про архиватор, поэтому вариант со стоп-символом точно не годится, Вы испортите большие бинарные файлы наверняка.

2021-02-27 13:10 UTC, yurii-litvinov requested changes
Больше похоже на правду, 4 балла из 7.

2021-02-27 13:10 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Trie.cs
> +        public int value;
Нельзя паблик-поля :)

2021-02-27 13:10 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Trie.cs
> +        public static int counter = 1;
public static нельзя вдвойне, тем более что он static не по делу --- если Вы в тесте, например, решите создать объект Trie, чтобы его потестить, и сделаете ему AddChild, это попортит основное дерево. Чтобы так не было, надо создать ещё один класс, Trie, а этот переименовать в TrieElement. Тогда Trie будет хранить корень и знать размер, а TrieElement --- хранить только то, что сейчас хранит в не-статик-полях. static --- это вообще очень специфичная штука, static-поля --- большая редкость в реальном коде.

2021-02-27 13:10 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Trie.cs
> +            Trie newChild = new Trie();
var

2021-02-27 13:10 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Trie.cs
> +        }
Однострочники лучше писать через `=>`

2021-02-27 16:06 UTC, Charlotte000 commented on semester2/Task2/Task2.1/LzwAlgorithm.cs
> +                File.Delete(compressedPath);
> В реальных программах так никогда не делайте, пользователь может важные данные потерять

В этом случае как правильно ?

2021-03-03 14:49 UTC, yurii-litvinov approved these changes
А всё (почти всё, за исключение пары технических деталей) круто. Зачтена, 7 баллов.

2021-03-03 14:49 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/LzwAlgorithm.cs
> +    class LzwAlgorithm
Самому классу на самом деле тоже нужен комментарий (даже больше, чем методам, потому что в объектно-ориентированных программах люди думают в терминах классов в основном)

2021-03-03 14:49 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/LzwAlgorithm.cs
> +    class LzwAlgorithm
И в классе только статические методы, так что он сам должен быть static (чтобы нельзя было написать var lzw = new LzwAlgorithm(); и думать, что имел в виду автор и почему так можно).

2021-03-03 14:49 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Program.cs
> +                        Console.WriteLine("File is already exists");
"File already exists" или "File does already exist" (что хуже), is exists --- это "он есть существует" :)

2021-03-03 14:49 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Trie.cs
> +    /// Prefix tree realization
"implementation". "realization" --- это скорее "понимание, осознание", чем "реализация"

2021-03-03 14:49 UTC, yurii-litvinov commented on semester2/Task2/Task2.1/Trie.cs
> +            private Hashtable children;
System.Collections.Generic.Dictionary лучше, он типобезопасный и кастать не надо при получении элемента

2021-03-03 16:06 UTC, merged