Task 4.1
Charlotte000/Homework pull request #6
Opened 2020-10-22 15:54 UTC by Charlotte000

2020-10-22 16:20 UTC, yurii-litvinov requested changes
В точности такое решение (за вычетом пары имён переменных и предварительного объявления функций) я уже видел тут: https://github.com/vad-ii-k/SPBU/pull/3/files. Если вы вместе делаете домашки, то хоть пишите, что вы их вместе делаете, чтобы я не смотрел два раза один и тот же код :) Попробуйте самостоятельно исправить замечания к коду Вашего коллеги.

2020-10-22 16:20 UTC, yurii-litvinov commented on Task4/4.1/4.1.vcxproj.user
> +﻿<?xml version="1.0" encoding="utf-8"?>
Этот файл не надо выкладывать, добавьте *.user в .gitignore

2020-10-22 18:37 UTC, Charlotte000 commented
> В точности такое решение (за вычетом пары имён переменных и предварительного объявления функций) я уже видел тут: https://github.com/vad-ii-k/SPBU/pull/3/files. Если вы вместе делаете домашки, то хоть пишите, что вы их вместе делаете, чтобы я не смотрел два раза один и тот же код :) Попробуйте самостоятельно исправить замечания к коду Вашего коллеги.

Списывать эти задания я точно бы не стал, думаю мой коллега тоже, так как задания эти тривиальны. Тем более делал я это задание уже давно. Спасибо за замечания. Исправил.

2020-10-24 10:37 UTC, yurii-litvinov requested changes
В целом всё правильно, только надо .user убрать

2020-10-24 10:37 UTC, yurii-litvinov commented on Task4/4.1/4.1.vcxproj.user
> +﻿<?xml version="1.0" encoding="utf-8"?>
Вы этот файл в .gitignore добавили, а из репозитория не убрали :)

2020-10-24 10:37 UTC, yurii-litvinov commented on Task4/4.1/4.1.c
> +			return false;
Лучше не выходить сразу при первом непрошедшем тесте, а дать и остальным отработать --- вдруг они ещё ошибок найдут

2020-10-28 10:40 UTC, yurii-litvinov approved these changes
Зачтена. Но никогда не называйте коммиты "Final fix" :)

2020-10-28 14:07 UTC, merged