Task 4.2
Charlotte000/Homework pull request #7
Opened 2020-10-22 15:57 UTC by Charlotte000

2020-10-24 10:48 UTC, yurii-litvinov requested changes
- Надо ещё .sln-ку для конкретно этого проекта
- Два предупреждения компилятора, надо исправить

2020-10-24 10:48 UTC, yurii-litvinov commented on Task4/4.2/4.2.c
> +		int number;
Неинициализированные переменные запрещены стайлгайдом

2020-10-24 10:48 UTC, yurii-litvinov commented on Task4/4.2/4.2.c
> +		fscanf(file, "%d", &number);
Имело бы смысл читать как `fscanf(file, "%*d");` --- * в форматном спецификаторе как раз означает "значение надо считать, но нам оно не нужно"

2020-10-24 10:48 UTC, yurii-litvinov commented on Task4/4.2/4.2.c
> +		return;
Файл останется незакрытым

2020-10-24 10:48 UTC, yurii-litvinov commented on Task4/4.2/4.2.c
> +	// �alculate the most frequent element
Кажется, тут русская "С"

2020-10-24 10:48 UTC, yurii-litvinov commented on Task4/4.2/Header.h
> +void quickSort(int*, int, int);
В заголовочном файле нужны комментарии ко всем функциям, и параметры у функций надо всегда именовать. Иначе пользоваться таким модулем будет очень сложно

2020-10-24 10:48 UTC, yurii-litvinov commented on Task4/4.2/Header.h
> +#pragma once
Header.h --- это ужасное название для заголовочного файла. Всё равно что "function" у функции

2020-10-24 10:48 UTC, yurii-litvinov commented on Task4/4.2/Header.h
> +void swapItems(int*, int*);
А это я вообще не уверен, что тут нужно --- модуль, наверное, должен предоставлять функциональность сортировки, а swapItems --- не сортировка. Принцип единственности ответственности нарушен.

2020-10-24 10:48 UTC, yurii-litvinov commented on Task4/4.2/Sort.c
> +void swapItems(int* a, int* b)
Первой строкой всегда надо подключать свой заголовочный файл. Чтобы компилятор мог проверить, что все сигнатуры функций совпадают

2020-10-24 18:15 UTC, Charlotte000 commented
> * Надо ещё .sln-ку для конкретно этого проекта
> * Два предупреждения компилятора, надо исправить

Как предупреждения убрать? Он ругается на неиспользованные переменные.

2020-10-28 11:18 UTC, yurii-litvinov requested changes
Всё ещё нужна .sln-ка. Та, что есть в корне репозитория, открывается с предупреждением, поскольку содержит ссылки на несуществующие проекты.

2020-10-28 11:18 UTC, yurii-litvinov commented on Task4/4.2/Sort.h
> +void quickSort(int* massive, int first, int last); // Quick sort realization
Комментарии пишутся на строке до комментируемой сущности, и отделяются пустой строкой от того, что выше. То есть правильно вот так:
```c
#pragma once

// Quick sort realization
void quickSort(int* massive, int first, int last);
```

2020-10-28 11:18 UTC, yurii-litvinov commented on Task4/4.2/4.2.c
> +	fclose(file);
main нарушает принцип единственности ответственности. Надо разбить на функции

2020-10-28 11:19 UTC, yurii-litvinov commented
Да, и тесты надо

2020-11-04 10:17 UTC, yurii-litvinov requested changes
Почти. 2.5 балла

2020-11-04 10:17 UTC, yurii-litvinov commented on Homework.sln
>  # Visual Studio Version 16
Ну так у Вас будет конфликт с мастером при каждом замердженном пуллреквесте. Чем плохо иметь несколько .sln-ок в репозитории?

2020-11-04 10:17 UTC, yurii-litvinov commented on Task4/4.2/4.2.c
> +	fclose(file);
Напоминаю

2020-11-04 10:17 UTC, yurii-litvinov commented on Task4/4.2/4.2.vcxproj.filters
> +    <Text Include="data4.2.txt" />
Его неплохо бы в "Файлы ресурсов" запихать

2020-11-04 18:47 UTC, Charlotte000 commented on Homework.sln
>  # Visual Studio Version 16
Просто у меня один Homework.sln на все задачи, я думал так удобнее

2021-02-13 10:00 UTC, merged