Task 4.3
Charlotte000/Homework pull request #8
Opened 2020-10-22 15:59 UTC by Charlotte000

2020-10-24 10:57 UTC, yurii-litvinov requested changes
Надо ещё тесты

2020-10-24 10:57 UTC, yurii-litvinov commented on Task4/4.3/4.3.c
> +	printf("0 - Exit\n1 - Create and save new phone\n2 - Get all phones\n3 - Find phone by name\n4 - Find phone by number\n");
Это лучше делат несколькими отдельными printf-ами, по одному на каждую строчку, чтобы в коде оно выглядело примерно как на консоли

2020-10-24 10:57 UTC, yurii-litvinov commented on Task4/4.3/4.3.c
> +		int input;
Неинициализированные переменные нельзя

2020-10-24 10:57 UTC, yurii-litvinov commented on Task4/4.3/4.3.c
> +			}
Это стоит вынести в отдельные функции, иначе Вы не сможете протестировать эту функциональность

2020-10-24 10:57 UTC, yurii-litvinov commented on Task4/4.3/4.3.vcxproj.user
> +﻿<?xml version="1.0" encoding="utf-8"?>
Это не надо

2020-10-24 18:23 UTC, Charlotte000 commented on Task4/4.3/4.3.c
> +		int input;
А как по другому? Она же заполняется только при вводе.

2020-10-28 12:39 UTC, yurii-litvinov requested changes
Почти всё ок, но надо больше тестов. Хорошие тесты должны как минимум покрывать все строчки кода, как максимум --- все пути исполнения (максимум, правда, недостижим из-за комбинаторного взрыва)

2020-10-28 12:39 UTC, yurii-litvinov commented on Task4/4.3/4.3.c
> +		return;
По-хорошему перед этим ещё надо сделать free(phone.name);, иначе мемлик

2020-10-28 12:39 UTC, yurii-litvinov commented on Task4/4.3/4.3.c
> +}
Тестовое покрытие слабовато. Функции поиска проверяются, а сохранения и загрузки --- совсем нет.

2020-11-04 10:21 UTC, yurii-litvinov requested changes

2020-11-04 10:21 UTC, yurii-litvinov commented on Task4/4.3/4.3.c
> +	savePhoneNumber(newPhone, 2);
Во-первых, утечка памяти, потому что в createPhoneNumber выделяется память под строки, но их никто не удаляет. Во-вторых, этот тест ничего не доказывает --- я могу сделать пустой savePhoneNumber и тест всё равно пройдёт.

2020-11-04 10:21 UTC, yurii-litvinov commented on Task4/4.3/4.3.c
> +	if (test() != true)
За `test() != true` одного бойца недавно чуть с комиссии не выгнали. Правильно `!test()`

2020-11-04 10:21 UTC, yurii-litvinov commented on Task4/4.3/4.3.c
> +			case 0: return;
loadPhoneNumber выделяет память. А освобождает ли её кто-нибудь?

2021-02-13 10:02 UTC, merged